import torch
import os
import json
from typing import Dict, Any

class SetupConfig:
    def __init__(self):
        self.gpu_count = torch.cuda.device_count() if torch.cuda.is_available() else 0
        self.cpu_count = os.cpu_count() or 1 # Ensure at least 1 CPU core for calculations
        self.total_gpu_memory = 0
        if self.gpu_count > 0:
            for i in range(self.gpu_count):
                self.total_gpu_memory += torch.cuda.get_device_properties(i).total_memory / (1024**3) # in GB

    def detect_optimal_config(self) -> Dict[str, Any]:
        """Detect optimal configuration based on available hardware."""
        config = {
            "mode": "cpu_only",
            "world_size": 1,
            "batch_size": 1,
            "max_length": 128,
            "gradient_accumulation_steps": 8,
            "learning_rate": 5e-5,
            "num_epochs": 3,
            "device": "cpu"
        }

        if self.gpu_count >= 1:
            config["device"] = "cuda"
            if self.gpu_count >= 2:
                # Multiple GPUs - distributed training
                config["mode"] = "distributed_gpu"
                config["world_size"] = self.gpu_count
                config["batch_size"] = 4
                config["max_length"] = 512
                config["gradient_accumulation_steps"] = 2
            else:
                # Single GPU - efficient single mode
                config["mode"] = "single_gpu"
                config["batch_size"] = 2
                config["max_length"] = 512
                config["gradient_accumulation_steps"] = 4
        
        # Adjust based on available CPU cores for multiprocessing (inference/self-chat)
        config["num_workers_cpu"] = max(1, self.cpu_count // 2) 

        print(f"Detected Hardware: GPUs={self.gpu_count}, CPUs={self.cpu_count}, Total GPU Memory={self.total_gpu_memory:.2f} GB")
        print(f"Optimal Configuration Detected: {config}")
        return config

    def generate_training_config_file(self, config: Dict[str, Any], filename: str = "training_config.py") -> str:
        """Generates a Python file with the detected training configuration."""
        content = f"""# This file is auto-generated by setup_config.py
# Do not modify manually unless you know what you are doing.

TRAINING_CONFIG = {json.dumps(config, indent=4)}

"""
        with open(filename, 'w') as f:
            f.write(content)
        return filename

if __name__ == "__main__":
    setup = SetupConfig()
    config = setup.detect_optimal_config()
    config_file = setup.generate_training_config_file(config)
    print(f"Generated training configuration file: {config_file}")